- name: Run Tests and send results
  run: |
    START_TIME=$(date +%s)
    pytest || TEST_STATUS="failed"
    END_TIME=$(date +%s)
    DURATION=$((END_TIME - START_TIME))
    TEST_STATUS=${TEST_STATUS:-passed}

    # Install Elasticsearch client
    pip install elasticsearch==8.15.0

    # Send results to Elasticsearch
    python - <<EOF
import os
from elastic_sender import send_ci_result

job_name = "ci-test"
status = os.environ.get("TEST_STATUS", "$TEST_STATUS")
duration = $DURATION

send_ci_result(job_name, status, duration)
EOF
