name: CI & System Monitoring

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/30 * * * *" # runs every 30 minutes

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  monitor-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Monitor GitHub
        run: |
          echo "Monitoring GitHub activity..."
